#!/bin/bash
#
# Copyright Amrith Kumar, 2017
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ -o RPI_VERBOSE ]; then set -ex; else set -e; fi

# users can specify DIB_DISTRO_NAME and DIB_DISTRO_URL so initialize
# those if they aren't being set.

DEFAULT_DISTRO_URL="http://mirrordirector.raspbian.org/raspbian"

export DIB_DISTRO_NAME=${DIB_DISTRO_NAME:=stretch}
export DIB_RELEASE=${DIB_DISTRO_NAME}
export DIB_DISTRO_URL=${DIB_DISTRO_URL:-$DEFAULT_DISTRO_URL}

# disk-image-builder requires all elements providing an operating
# system to also export a DISTRO_NAME.

export DISTRO_NAME="debian"
export DEBIAN_FRONTEND=noninteractive

export DIB_DISABLE_APT_CLEANUP=${DIB_DISABLE_APT_CLEANUP:-0}
