#!/bin/bash
#
# Copyright Amrith Kumar, 2017
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ -o RPI_VERBOSE ]; then set -ex; else set -e; fi

set -ex

_MYPATH=$(dirname $0)

TMP_PATH=${TMP_HOOKS_PATH}/rpi-extradata
mkdir -p ${TMP_PATH}

cp -v ${_MYPATH}/files/* ${TMP_PATH}

_DUC_PATH="/tmp/noip-duc-linux.tar.gz"

wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz -O ${_DUC_PATH}

cp -v ${_DUC_PATH} ${TMP_PATH}

if [ ! -z "${RPI_NOIP_CONFIG_FILE-}" ]; then
    cp "${RPI_NOIP_CONFIG_FILE-}" ${TMP_PATH}/rpi-noip-config-file
fi
