#!/bin/bash
#
# Copyright Amrith Kumar, 2017
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ -n ${RPI_VERBOSE} ]; then set -ex; else set -e; fi

_MYPATH=$(dirname $0)

TMP_PATH=${TMP_HOOKS_PATH}/rpi-extradata
mkdir -p ${TMP_PATH}

cp -v ${_MYPATH}/files/* ${TMP_PATH}

# if the user running this has an authorized_keys file, use that and
# if that doesn't, use the users public key.
if [ -e ~/.ssh/authorized_keys ]; then
    cp -v ~/.ssh/authorized_keys ${TMP_PATH}/authorized_keys
else
    [ -e ~/.ssh/id_rsa.pub ]

    cp -v ~/.ssh/id_rsa.pub ${TMP_PATH}/authorized_keys
fi
