#!/bin/bash
#
# Copyright Amrith Kumar, 2017
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ -o RPI_VERBOSE ]; then set -ex; else set -e; fi

[ ! -z "${RPI_SSID}" ]
[ ! -z "${RPI_WIFI_PASSPHRASE}" ]

TMP_HOOKS_DIR="/tmp/in_target.d/rpi-extradata"

[ -d ${TMP_HOOKS_DIR} ]

_FNAME="interfaces"

[ -f ${TMP_HOOKS_DIR}/${_FNAME} ]

PSK=$(wpa_passphrase ${RPI_SSID} ${RPI_WIFI_PASSPHRASE} | grep '[[:blank:]]psk' | cut -f 2 -d '=')

cat ${TMP_HOOKS_DIR}/${_FNAME} | sed "s/SSID/${RPI_SSID}/" | sed "s/PSK/${PSK}/" > /etc/network/interfaces

chmod 600 /etc/network/interfaces

cat /etc/network/interfaces
