#!/bin/bash
#
# Copyright Amrith Kumar, 2017
#
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

if [ -o RPI_VERBOSE ]; then set -ex; else set -e; fi

_LDSO_DISABLED="${TARGET_ROOT}/etc/ld.so.preload.disabled"
_LDSO="${TARGET_ROOT}/etc/ld.so.preload"

if [ -e ${_LDSO_DISABLED} ]; then
    sudo mv ${_LDSO_DISABLED} ${_LDSO}
fi
